---
- name: Deploy Open Source App on Ubuntu with Apache
  hosts: master, slave1
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is running
      systemd:
        name: apache2
        state: started
        enabled: true

    # - name: Copy Apache configuration file
    #   template:
    #     src: apache.conf.j2
    #     dest: /etc/apache2/apache2.conf
    #   notify: Restart Apache

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ app_dependencies  }}"

    - name: Deploy the app
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dest }}"
        version: "{{ app_version }}"
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2 
        state: restarted
        enabled: true

- name: Deploy Open Source App on Cent OS with Apache
  hosts: slave2
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Enable Apache service
      systemd:
        name: httpd
        enabled: yes

    # - name: Ensure Apache service is running
    #   service:
    #     name: httpd
    #     state: started
        # enabled: true

    # - name: Copy Apache configuration file
    #   template:
    #     src: apache.conf.j2
    #     dest: /etc/httpd/conf/httpd.conf
    #   notify: Restart Apache

    - name: Install dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ app_dependencies  }}"

    - name: Install Firewalld
      yum:
        name: firewalld
        state: present

    - name: Ensure Firewalld is running
      service: 
        name: firewalld
        state: started
        enabled: yes

    - name: Deploy the app
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dest }}"
        version: "{{ app_version }}"
      notify: Restart Apache

  handlers:
    - name: Restart Firewalld
      systemd:
        name: firewalld 
        state: restarted
        enabled: yes
    - name: Restart Apache
      systemd:
        name: httpd 
        state: restarted
        enabled: yes

